# Generated by Django 5.2 on 2025-05-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesection',
            name='section_type',
            field=models.CharField(choices=[('abstract', 'Abstract'), ('introduction', 'Introduction'), ('method', 'Method'), ('stimuli', 'Stimuli'), ('subject', 'Subject'), ('procedure', 'Procedure'), ('data_acquisition', 'Data acquisition and analysis'), ('equipment', 'Equipment'), ('results', 'Results'), ('discussion', 'Discussion'), ('conclusion', 'Conclusion'), ('analysis', 'In-depth Analysis'), ('arguments', 'Logical Arguments'), ('literature_review', 'Literature Review'), ('synthesis', 'Synthesis'), ('case_study', 'Case Study'), ('implications', 'Practical Implications'), ('limitations', 'Limitations'), ('acknowledgments', 'Acknowledgments')], max_length=100, verbose_name='Section Type'),
        ),
        migrations.AlterField(
            model_name='articletemplatesection',
            name='section_type',
            field=models.CharField(choices=[('abstract', 'Abstract'), ('introduction', 'Introduction'), ('method', 'Method'), ('stimuli', 'Stimuli'), ('subject', 'Subject'), ('procedure', 'Procedure'), ('data_acquisition', 'Data acquisition and analysis'), ('equipment', 'Equipment'), ('results', 'Results'), ('discussion', 'Discussion'), ('conclusion', 'Conclusion'), ('analysis', 'In-depth Analysis'), ('arguments', 'Logical Arguments'), ('literature_review', 'Literature Review'), ('synthesis', 'Synthesis'), ('case_study', 'Case Study'), ('implications', 'Practical Implications'), ('limitations', 'Limitations'), ('acknowledgments', 'Acknowledgments')], max_length=100, verbose_name='Section Type'),
        ),
        migrations.AlterField(
            model_name='researchprojectsection',
            name='section_type',
            field=models.CharField(choices=[('subject', 'Subject'), ('stimuli', 'Stimuli'), ('equipment', 'Equipment'), ('materials', 'Materials/Instruments'), ('procedure', 'Procedure'), ('data_acquisition', 'Data acquisition and analysis'), ('ethical_considerations', 'Ethical Considerations')], max_length=100, verbose_name='Section Type'),
        ),
        migrations.AlterField(
            model_name='researchprojecttemplatesection',
            name='section_type',
            field=models.CharField(choices=[('subject', 'Subject'), ('stimuli', 'Stimuli'), ('equipment', 'Equipment'), ('materials', 'Materials/Instruments'), ('procedure', 'Procedure'), ('data_acquisition', 'Data acquisition and analysis'), ('ethical_considerations', 'Ethical Considerations')], max_length=100, verbose_name='Section Type'),
        ),
    ]
