# Generated by Django 5.2 on 2025-04-17 18:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesection',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='booksection',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Table Content'),
        ),
        migrations.AlterField(
            model_name='researchprojectsection',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='expected_results',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Expected Results'),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='literature_review',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Literature Review'),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='problem_statement',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Problem Statement'),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='research_importance',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Research Importance'),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='research_methodology',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Research Methodology'),
        ),
        migrations.AlterField(
            model_name='researchproposal',
            name='research_objectives',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Research Objectives'),
        ),
        migrations.AlterField(
            model_name='researchproposalsection',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='thesissection',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content'),
        ),
    ]
