# Generated by Django 5.2 on 2025-04-27 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='cited_content_type',
            field=models.ForeignKey(default='article', limit_choices_to={'model__in': ['article', 'book', 'thesis']}, on_delete=django.db.models.deletion.CASCADE, related_name='cited_references', to='contenttypes.contenttype'),
        ),
    ]
