# Generated by Django 5.2 on 2025-04-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_articlesection_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='DOI'),
        ),
    ]
