# Generated by Django 5.2 on 2025-04-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_reference_cited_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(blank=True, choices=[('research', 'Research Article'), ('review', 'Review Article'), ('analytical', 'Analytical Article'), ('descriptive', 'Descriptive Article'), ('theoretical', 'Theoretical Article'), ('short', 'Short Communication'), ('survey', 'Survey Article'), ('narrative', 'Narrative Article'), ('editorial', 'Editorial'), ('practical', 'Practical Article')], max_length=100, verbose_name='Article Type'),
        ),
    ]
