# Generated by Django 5.2 on 2025-04-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_article_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchprojectsection',
            name='section_type',
            field=models.CharField(choices=[('subject', 'Subject'), ('stimuli', 'Stimuli'), ('materials', 'Materials/Instruments'), ('procedure', 'Procedure'), ('data_acquisition', 'Data acquisition and analysis'), ('data_analysis', 'Data Analysis'), ('ethical_considerations', 'Ethical Considerations')], max_length=100, verbose_name='Section Type'),
        ),
        migrations.AlterField(
            model_name='researchprojecttemplatesection',
            name='section_type',
            field=models.CharField(choices=[('subject', 'Subject'), ('stimuli', 'Stimuli'), ('materials', 'Materials/Instruments'), ('procedure', 'Procedure'), ('data_acquisition', 'Data acquisition and analysis'), ('data_analysis', 'Data Analysis'), ('ethical_considerations', 'Ethical Considerations')], max_length=100, verbose_name='Section Type'),
        ),
    ]
